### ISSUE TITLE
Error installing keras in open suse

### ISSUE THREAD

**Issue by Amaravati** [jangirrishabh/toyCarIRL#2]
Hi Rishab,
                 I am getting error while installing keras in open suse. I did install python 3. While installing keras am getting error message like: command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-70_05rwz/h5py. Can you please let me know which ubuntu version you have used and if you can provide me the link for iso file, it would be greatly helpful

Thanks
Anvesha

**Comment by jangirrishabh** [comment]
Hello Anvesha, my workstation runs Ubuntu 14.04, and I don't remember any such issues while installing Keras. Try and follow the parent blog which I have mentioned, I hope they have covered the instructions to install Keras.

**Comment by Amaravati** [comment]
Hi Rishab,
                Thanks for response. I was able to install and get the code working. How long simulations took for you for 64, 150 layered network? Do you use GPU? Did you implement the obstacle avoidance robot in any board?
               Looking forward to your reply.
Thanks
Anvesha

**Comment by jangirrishabh** [comment]
My work focuses on making the agent learn various kinds of behaviors, for learning each behavior it took around 1 hour, and I even restricted it up to 2000 iterations. Yes I was using a GPU, and I did not implement it on a board.
