### ISSUE TITLE
IRL Algorithm derived from?

### ISSUE THREAD

**Issue by anitaramasamy3** [jangirrishabh/toyCarIRL#5]
Hi, I was wondering which paper you implemented the algorithm from. You cited two.

**Comment by jangirrishabh** [comment]
Ng and Russell, 2000 is the parent paper where the theory of IRL was formulated, and the implemented algorithm is a version from Abbeel and Ng, 2004, hope this helps

**Comment by anitaramasamy3** [comment]
Thanks a lot! Great work!
