### ISSUE TITLE
What does the expert policy describe?

### ISSUE THREAD

**Issue by matriculus** [jangirrishabh/toyCarIRL#6]
I would like to know what those 8 values in expert policy define. I want to implement in another system for obstacle avoidance. I don't understand how the trajectory is provided to the irl agent.

**Comment by jangirrishabh** [comment]
Hello @pradeeshenator the values in the expert policy are Feature expectations which is the sum of discounted feature values. These feature values are defined manually for this particular agent, feel free to experiment with them. For more information check out the blog IRL/[https://jangirrishabh.github.io/2016/07/09/virtual-car-IRL/](url)
